# Site settings
title: Sam Baxter
motto: >
  I am a first year PhD student at UMass Amherst working in the
  <a href="http://plasma.cs.umass.edu"">PLASMA Lab</a> with
  <a href="http://http://people.cs.umass.edu/~arjun">Arjun Guha</a>.
  Before this I worked at <a href="https://www.izotope.com/">iZotope,
  Inc.</a> developing desktop audio software and hacking together Linux
  device drivers. My research interests are programming languages
  and building and verifying systems.
email: sbaxter@cs.umass.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://baxtersa.github.io" # the base hostname & protocol for your site
github_username:  baxtersa

# Build settings
markdown: kramdown
